### ISSUE TITLE
Cleanup Starter Crate Content

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#444]
Categorize and readjust content.

**Todo**
- [ ] Move magazines to common category
- [ ] Add medical equipment to common
- [ ] Add common equipment to common. 
- [ ] Check weapons
- [ ] Check frags (Use ace modded frag depricated RHS)
- [ ] Check smokes (Use Vanilla ace modded)
- [ ] Add PMAG mags to Charlie cat (will cause both STANG and PMAG to be pressent in Charlie but it's fine.) 

Handle Charlie Crate in Charlie Loadout Update #422

**Comment by ColdEvul** [comment]
#443

**Comment by ColdEvul** [comment]
#338

**Comment by Robot-Panda15** [comment]
Charlie is currently utilizing the PMAGs, might want to look into replacing the normal STANAGS with that for ammo

**Comment by ColdEvul** [comment]
@Robot_Panda15#9906 Are you interesting in helping out with this?

**Comment by ColdEvul** [comment]
awesome good point. 
Was about to ask if you could help me out with this.

**Comment by ColdEvul** [comment]
i think it whould be fine to mix it :)
