### ISSUE TITLE
Broströms Todo

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#570]
- [ ] Fix jump script to include all valid aircrafts.
- [x] Add the Alpha Flag and insignia 
- [x] Add the insignia from pm
- [x] Check the loadouts
