### ISSUE TITLE
C/1-7 USP Loadout Checklist

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/cScripts#844]
Working with C/1-7 - this is a to-do list.

**Create Loadouts:**
- [ ] Rifleman
- [ ] Grenadier
- [ ] Standalone M320 Grenadier
- [ ] Automatic Rifleman
- [ ] Fire Team Leader
- [ ] Squad Leader
- [ ] Platoon Medic - @mazinskihenry 
- [ ] Platoon Sergeant/Platoon Staff
- [ ] Platoon Leader
- [ ] Weapons Squad Leader
- [ ] M240 Team Leader
- [ ] M240 Machine Gunner
- [ ] M240 Assistant Gunner
- [ ] MAAWS Team Leader
- [ ] MAAWS Gunner
- [ ] MAAWS Assistant Gunner
------------------------------------------------------------------------------------------------------------------------------------
**Update Arsenal Whitelist**
- [ ] Crye G3C Multicam Uniform
- [ ] Ops-Core FAST Helmet (MC)
- [ ] Syntex 45L Backpack (MC)
- [ ] Crye Zip-On Panel RF/RF2 (MC)
- [ ] FSP Strandhogg Loadout (MC)
- [ ] Eagle MBAV Loadout (Tan)
- [ ] Crye JPC (MC)
- [ ] TA31RCO-RMR
- [ ] SU-230PVS MRDS (A) Model for M240
- [ ] G33 + XPS3
- [ ] G33 + SU-278
- [ ] M68 CCO
- [ ] SU-278 LT660
- [ ] Glock 17 (AR, PLTHQ, and M240 Gunners Only)
- [ ] M320 Standalone (PLTHQ)
- [ ] TD Stubby Grip
- [ ] TD Vertical
- [ ] RVG Grip
- [ ] AFG Grip
- [ ] Eagle A-III OCP Raven (PLTHQ)
- [ ] AN/PEQ-15/M952V
- [ ] AN/PEQ-15 (Top)
- [ ] AN/PEQ-15 + WMX
